= Uživatelská dokumentace – Časopis Křídlo
:lang: cs
:doctype: book

:toc: left
:toc-title: Obsah

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Úvod

Vítejte v uživatelské dokumentaci k systému časopisu Křídlo. Tento dokument poskytuje podrobné informace o jeho funkcích a jejich použití.
Aplikace systému je v současné době provozována na adrese https://alpha.kts.vspj.cz/~halvova/rsp.

== Základní funkce

=== Přihlášení

Pro přihlášení do systému postupujte následovně:

1. Na výchozí stránce časopisu je v pravém horním rohu tlačítko "Přihlášení"
2. Po vyplnění "Uživatelského jména" a "Hesla" se údaje potvruzjí modrým tlačítkem "Přihlásit se"
3. Při nesprávně zadaných údajích je uživatel informován vyskakovací notifikací.
4. Při správně zadaných údajích je uživateli zobrazena úvodní stránka. Menu poté odpovídá roli přihlášeního uživatele
5. Informace k jednotlivým rolím následují v dokumentaci níže

Po ukončení práce na stránce má uživatel možnost se odhlásit tlačítkem "Odhlásit se" v pravém horním rohu. Uživatel je poté odhlášen a přesměrován na úvodní stránku pro nepřihlášené uživatele.

=== Přehled vydaných článků

Jako čtenář máte možnost prohlížet vydané články přímo na úvodní stránce systému. Postupujte následovně:

1. Přejděte na úvodní stránku systému.
2. Zde naleznete seznam všech publikovaných článků.
3. Pro zobrazení konkrétního článku klikněte na tlačítko "Otevřít článek".

TIP: Využijte funkce filtrování a řazení pro efektivní procházení vydaných článků.

=== Moje články
IMPORTANT: Funkce vyžaduje přihlášení a uživatelskou roli *AUTOR*.

Záložka moje články slouží pro správu vámi nabízených článků. To zahrnuje možnost nabídnutí nového článku či kompletní přehled a historii vámi nabízených článků s možností jejich zobrazení. Pro zobrazení konkrétního článku klikněte na tlačítko "Otevřít článek".

TIP: Své články můžete filtrovat podle názvu vyplněním příslušného pole pro vyhledávání.

==== Nabídnutí a vložení článku

Pro nabídnutí nového článku a jeho vložení do systému postupujte následovně:

1. Na hlavním menu zvolte záložku "Moje články".
2. Klikněte na tlačítko "Nový článek", které vyvolá vytvářecí formulář.
3. Z rozevírací nabídky zvolte jedno z nabízených tematických čísel časopisu. U každé z nabízených položek pak vedle samotného tématu vidíte v závorce i související charakteristiky ve formátu *ZÁJEM/PŘIJATO/KAPACITA*.
* *ZÁJEM*: Aktuální zájem o dané číslo, tj. celkový počet příspěvků v recenzním řízení.
* *PŘIJATO*: Počet příspěvků, které úspěšně prošly recenzním řízení a budou do daného čísla zařazeny.
* *KAPACITA*: Maximální počet příspěvků, které mohou být zařazeny do daného čísla.
4. Vyplňte název svého článku.
5. Zvolte soubor s plným textem článku z vašeho zařízení, který bude posléze nahrán do systému.
6. Pokud se na článku podílelo více autorů, uveďte i ostatní členy autorského týmu pomocí tlačítka "Vyhledat autora". Je možné, že daný autor prozatím nebude veden v evidenci časopisu Křídlo; v takovém případě využijte tlačítka "Přidat nového autora" a vyplňte jeho kontaktní údaje.
7. Ujistěte se, že jste vyplnili všechny informace správně, a dokončete nabídnutí článku tlačítkem "Vložit článek".

NOTE: Podporovanými formáty souboru článku jsou pouze dokumenty typu PDF a DOC(X). Název souboru nesmí obsahovat diakritiku, jako jsou háčky nebo čárky.

==== Recenzní řízení článku

Pro zjištění aktuálního stavu recenzního řízení ke svému článku nejprve najděte konkrétní článek v seznamu svých článků, kde ve sloupci "Stav" uvidíte jednu z následujích možností:

* *NOVĚ PODANÝ*: Recenzní řízení nebylo dosud zahájeno, probíhá zvolení recenzentů pro Váš článek.
* *V PROCESU*: Recenzní řízení bylo zahájeno, čeká se na vypracovaní a vyhodnocení recenzí
daného čísla 
* *ZVEŘEJNĚNÝ*: Váš článek prošel úspěšně recenzním řízením a stává se součastí daného tematického čísla časopisu.
* *ZAMÍTNUTÝ*: Váš článek neprošel recenzním řízením a nebude uveřejněn.

Pro zobrazení veškerých recenzí Vašeho článku klikněte u vybraného článku na tlačítko "Zobrazit recenze". Následně uvidíte přehled recenzí společně s informací o jejich původci a datu vypracování. Faktory s výpovědní hodnotou pak představují známky pro jednotlivé hodnotící kategorie na stupnici 1–5, kde 1 znamená nejlepší a 5 nejhorší, a písemné vyjádření recenzenta, které si zobrazíte kliknutím na tlačítko "Zobrazit vyjádření".

NOTE: V případě, že nesouhlasíte se závěry dané recenze, uveďte své námitky do oponentního formuláře po kliknutí na tlačítko "Kontaktovat redaktora".

=== Nové články
IMPORTANT: Funkce vyžaduje přihlášení a uživatelskou roli *REDAKTOR*.

Záložka nové články slouží pro správu nově přidaných článků redaktorem. To zahrnuje možnost Zveřejnění či zamítnutí článku. Pro zobrazení konkrétního článku klikněte na tlačítko "Otevřít článek".

TIP: Články můžete filtrovat podle názvu vyplněním příslušného pole pro vyhledávání a řadit podle názvu, autora nebo tématu časopisu kliknutím na text v příslušné buňce hlavičky tabulky.

Pro zveřejnění článku postupujte následnovně:

1. Na hlavním menu zvolte záložku "Nové články".
2. Klikněte na zelené tlačítko "Zveřejnit článek".
3. Zobrazí se vyskakovací okno, pro zveřejnění klikněte na "OK", pokud si článek nepřejete zveřejnit, klikněte na "Zrušit".
4. Kliknutím na "OK" se článek zveřejní a tudíž zmizí z přehledu nových článků.

Pro zamítnutí článku postupujte následnovně:

1. Na hlavním menu zvolte záložku "Nové články".
2. Zobrazí se seznam nových článků. Klikněte na červené tlačítko "Zamítnout článek" pro zamítnutí článku.
3. Zobrazí se vyskakovací okno, pro zamítnutí klikněte na "OK", pokud si článek nepřejete zamítnout, klikněte na "Zrušit".
4. Kliknutím na "OK" se článek zamítne a autor obdrží notifikaci o zamítnutí.

=== Přehled všech článků
IMPORTANT: Funkce vyžaduje přihlášení a uživatelskou roli *REDAKTOR*.

Záložka přehled všech článků slouží pro prohlížení a správu všech článků redaktorem. To zahrnuje možnost Zveřejnění či zamítnutí článku. Pro zobrazení konkrétního článku klikněte na tlačítko "Otevřít článek".

TIP: Články můžete filtrovat podle názvu vyplněním příslušného pole pro vyhledávání a filtrovat podle stavu kliknutím na šedé tlačítko vedle nápisu "Stav" v hlavičce tabulky.

Pro zveřejnění článku postupujte následnovně:

1. Na hlavním menu zvolte záložku "Přehled všech článků".
2. Klikněte na zelené tlačítko "Zveřejnit článek".
3. Zobrazí se vyskakovací okno, pro zveřejnění klikněte na "OK", pokud si článek nepřejete zveřejnit, klikněte na "Zrušit".
4. Kliknutím na "OK" se změní stav článku na "Zveřejněný".

Pro zamítnutí článku postupujte následnovně:

1. Na hlavním menu zvolte záložku "Přehled všech článků".
2. Zobrazí se seznam nových článků. Klikněte na červené tlačítko "Zamítnout článek" pro zamítnutí článku.
3. Zobrazí se vyskakovací okno, pro zamítnutí klikněte na "OK", pokud si článek nepřejete zamítnout, klikněte na "Zrušit".
4. Kliknutím na "OK" se článek zamítne a autor obdrží notifikaci o zamítnutí.

=== Archivace článků - Autor - přidání nové verze
IMPORTANT: Funkce vyžaduje přihlášení a uživatelskou roli *AUTOR*

Funkce slouží autorovi k přidání nové verze článku. Je dostupná na záložce "Moje články". Pro nahrání nové verze článku slouží tlačítko "Editovat" v příslušném řádku seznamu článků.
Funkce notifikuje recenzenta o nahrání nové verze článku na platformě autorem. Recenzentovi se zobrazí v záložce zprávy nová, nepřečtená zpráva.  

1. Na hlavním menu zvole záložku "Moje články".
2. V seznamu článků u článku, který chcete revidovat klidněte ve sloupci "Verze" na modré tlačítko "Editovat".
3. Zobrazí se vyskakovací okno, je možné změnit název článku. Obsah nové revize nahrajete přiložením souboru pomocí šedého tlačítka "Zvolit soubor".
4. Potvrzením pomocí modrého tlačítka "Uložit změny" dojde k nahrání nové verze článku.
5. V seznamu článků se inkrementuje čítač verze a pod možností "Otevřít článek" bude dostupná nejnovější nahraná verze článku.

=== Archivace článků - Redaktor - přehled verzí článků
IMPORTANT: Funkce vyžaduje přihlášení a uživatelskou roli *REDAKTOR*

Funkce slouží redaktorovi k přehledu o počtu revizí jednotlivých článků, dále má možnost pro každý článek zjistit historii verzí, včetně jejich plných znění.

1. Na hlavním menu zvole záložku "Přehled všech článků".
2. V seznamu článků je sloupec "Verze" obsahující číslo a modré tlačítko "Zobrazit verze".
3. Číslo udává kolikátá revize článku je nejnovější.
4. Tlačítkem "Zobrazit verze" dojde k přesměrování na nový seznam, kde jsou vypsané sestupně všechny verze zvoleného článku.
5. K dispozici je i soubor, který byl přiložený při vytváření verze autorem pomocí tlačítka "Otevřít článek".

=== Archivace článků - Autor - přidání nové verze
IMPORTANT: Funkce vyžaduje přihlášení a uživatelskou roli *AUTOR*

Funkce slouží autorovi k přidání nové verze článku. Je dostupná na záložce "Moje články". Pro nahrání nové verze článku slouží tlačítko "Editovat" v příslušném řádku seznamu článků.
Funkce notifikuje recenzenta o nahrání nové verze článku na platformě autorem. Recenzentovi se zobrazí v záložce zprávy nová, nepřečtená zpráva.  

1. Na hlavním menu zvole záložku "Moje články".
2. V seznamu článků u článku, který chcete revidovat klidněte ve sloupci "Verze" na modré tlačítko "Editovat".
3. Zobrazí se vyskakovací okno, je možné změnit název článku. Obsah nové revize nahrajete přiložením souboru pomocí šedého tlačítka "Zvolit soubor".
4. Potvrzením pomocí modrého tlačítka "Uložit změny" dojde k nahrání nové verze článku.
5. V seznamu článků se inkrementuje čítač verze a pod možností "Otevřít článek" bude dostupná nejnovější nahraná verze článku.

=== Vytváření recenze
IMPORTANT: Funkce vyžaduje přihlášení a uživatelskou roli *RECENZENT*

Funkce slouží recenzentovi k přidání recenze k danému článku.

1. Na hlavním menu zvole záložku "Články k recenzi".
2. V seznamu článků k recenzi je sloupec "Vytvořit recenzi" obsahující modré tlačítko "Vytvořit recenzi".
3. Po kliknutí na tlačítko se otevře modální okno.
4. Recenzent zvolí hodnocení (1-5) pro Aktuálnost, Zajímavost a přínostnost, Originalitu a odbornou úroveň, Jazykovou a stylistickou úroveň.
5. Recenzent Přidá textový komentář.
6. Pokud jsou všechny položky vyplněné, může kliknout na tlačítko Uložit recenzi.
7. Recenze se uloží a Redaktor ji má k dispozici v jeho předhledu článků.
8. Článek zmizí z přehledu Článků k recenzi.
